AWSTemplateFormatVersion: 2010-09-09
Description: "Setup the Application Load Balancer"
Parameters:
  ALBSG:
    Type: "AWS::EC2::SecurityGroup::Id"
    Description: Enter a valid security group ID for Application Load Balancer
  VPCID:
    Type: "AWS::EC2::VPC::Id"
    Description: Input the VPC ID
  PublicSubnetA:
    Type: "AWS::EC2::Subnet::Id"
    Description: Enter the Subnet ID for SubnetPublicA
  PublicSubnetB:
    Type: "AWS::EC2::Subnet::Id"
    Description: Enter the Subnet ID for SubnetPublicA
  PublicSubnetC:
    Type: "AWS::EC2::Subnet::Id"
    Description: Enter the Subnet ID for SubnetPublicA
Resources:
  ALB:
    Type: "AWS::ElasticLoadBalancingV2::LoadBalancer"
    Properties:
      IpAddressType: "ipv4"
      Scheme: "internet-facing"
      SecurityGroups:
        - !Ref ALBSG
      Subnets:
        - !Ref PublicSubnetA
        - !Ref PublicSubnetB
        - !Ref PublicSubnetC
      Tags:
        - Key: Name
          Value: !Join ["", ["SKYELP-ALB-", !Ref "AWS::StackName"]]
      Type: "application"
  ALBListener:
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ALBTargetGroup
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: HTTP
  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /healthcheck.html
      HealthCheckTimeoutSeconds: 5
      Port: 80
      Protocol: HTTP
      UnhealthyThresholdCount: 5
      VpcId: !Ref VPCID
Outputs:
  WordpressURL:
    Description: WordpressURL
    Value: !Join ["", ["http://", !GetAtt ALB.DNSName]]
    Export:
      Name: wordpress-app-loadbalancer-url
