AWSTemplateFormatVersion: 2010-09-09
Description: "Setup RDS for Wordpress"
Parameters:
  RDSMultiAZ:
    Description: Select True if you want to use Multi AZ, additional AWS charges will apply
    Type: "String"
    Default: "False"
    AllowedValues:
      - "True"
      - "False"
  DatabaseName:
    Description: "If there is no snapshot, specify a DB name (Must be a valid name containing alphanumeric characters, or any of the following: -/_+=.@!)"
    Type: String
  RDSSG:
    Type: "AWS::EC2::SecurityGroup::Id"
    Description: Enter the security group ID for RDS
  DataSubnetA:
    Type: "AWS::EC2::Subnet::Id"
    Description: Enter the Subnet ID for SubnetDataA
  DataSubnetB:
    Type: "AWS::EC2::Subnet::Id"
    Description: Enter the Subnet ID for SubnetDataB
  DataSubnetC:
    Type: "AWS::EC2::Subnet::Id"
    Description: Enter the Subnet ID for SubnetDataC
Resources:
  SecretsManagerRDSCredentials:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Description: AWS RDS admin credentials
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: password
        PasswordLength: 32
        ExcludePunctuation: True
  SecretsManagerRDSInstanceAttachment:
    Type: "AWS::SecretsManager::SecretTargetAttachment"
    Properties:
      SecretId:
        Ref: SecretsManagerRDSCredentials
      TargetId:
        Ref: DB
      TargetType: "AWS::RDS::DBInstance"
  RDSSubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      DBSubnetGroupDescription: RDS Subnet Groups
      SubnetIds:
        - Ref: DataSubnetA
        - Ref: DataSubnetB
        - Ref: DataSubnetC
  DB:
    Type: "AWS::RDS::DBInstance"
    DeletionPolicy: Delete
    Properties:
      AllocatedStorage: "20"
      DBInstanceClass: "db.t2.micro"
      DBInstanceIdentifier: WordPressDB
      DBSubnetGroupName:
        Ref: RDSSubnetGroup
      DBName:
        Ref: DatabaseName
      Engine: MySQL
      EngineVersion: "8.0.28"
      MasterUsername:
        Fn::Sub: "{{resolve:secretsmanager:${SecretsManagerRDSCredentials}::username}}"
      MasterUserPassword:
        Fn::Sub: "{{resolve:secretsmanager:${SecretsManagerRDSCredentials}::password}}"
      MultiAZ:
        Ref: RDSMultiAZ
      StorageType: gp2
      Tags:
        - Key: Name
          Value: "WP-RDS-DB"
      VPCSecurityGroups:
        - Ref: RDSSG
Outputs:
  exportDBname:
    Description: "Export DB name"
    Value:
      Ref: DatabaseName
    Export:
      Name: skyelp-db-name
  exportDBaddress:
    Description: "Export DB address"
    Value:
      Fn::GetAtt: DB.Endpoint.Address
    Export:
      Name: skyelp-db-endpoint
  exportRDSSecretsARN:
    Description: "Export the arn for the SecretsManagerRDSCredentials"
    Value:
      Ref: SecretsManagerRDSCredentials
    Export:
      Name: skyelp-secretsmanager-arn
