AWSTemplateFormatVersion: 2010-09-09
Description: "IAM Roles, Policys used accross the Wordpress Architecture"
Parameters:
  RDSSecretsARN:
    Type: "String"
    Description: "Enter the arn from RDS Secrets Manager"
Resources:
  RDSSecretsReadPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      Description: "Managed Policy to allow Wordpress EC2 Read Access to SecretsManagerRDSCredentials"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - "secretsmanager:GetSecretValue"
            Resource:
              - Ref: RDSSecretsARN
  WordpressRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Path: /
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy"
        - "arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess"
        - "arn:aws:iam::aws:policy/AmazonElasticFileSystemClientFullAccess"
        - "arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess"
        - "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
        - Ref: RDSSecretsReadPolicy
  WordpressInstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: /
      Roles:
        - Ref: WordpressRole
Outputs:
  exportWordpressInstanceProfile:
    Description: "Export Wordpress EC2 Instance Profile ARN"
    Value:
      Fn::GetAtt: ["WordpressInstanceProfile", "Name"]
    Export:
      Name: skyelp-wordpress-instanceprofile
  exportWordpressRole:
    Description: "Export Wordpress EC2 Instance Role"
    Value:
      Ref: WordpressRole
    Export:
      Name: skyelp-wordpress-instancerole
